# Linear Algebra II: Matrix Operations

This topic, *Linear Algebra II: Matrix Operations*, builds on the basics of linear algebra. It is essential because these intermediate-level manipulations of tensors lie at the heart of most machine learning approaches and are especially predominant in deep learning. 

Through the measured exposition of theory paired with interactive examples, you’ll develop an understanding of how linear algebra is used to solve for unknown values in high-dimensional spaces as well as to reduce the dimensionality of complex spaces. The content covered in this topic is itself foundational for several other topics in the *Machine Learning Foundations* series, especially *Probability & Information Theory* and *Optimization*. 

## Segment 1: Review of Introductory Linear Algebra

In [2]:
import numpy as np

In [3]:
x = np.array([25, 2, 5])
x

array([25,  2,  5])

In [4]:
x.shape

(3,)

In [5]:
x = np.array([[25, 2, 5]])
x

array([[25,  2,  5]])

In [6]:
x.shape

(1, 3)

In [7]:
x.T

array([[25],
       [ 2],
       [ 5]])

In [8]:
x.T.shape

(3, 1)

## $L^2$ Norm

In [9]:
x

array([[25,  2,  5]])

In [10]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [11]:
np.linalg.norm(x)

25.573423705088842

### Matrices

In [14]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [15]:
X.shape

(3, 2)

### Matrix Transposition

In [16]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [17]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

### Matrix Multiplication

In [18]:
X*3

array([[75,  6],
       [15, 78],
       [ 9, 21]])

In [19]:
X*3+3

array([[78,  9],
       [18, 81],
       [12, 24]])

Using the multiplication operator on two tensors of the same size in Numpy or TensorFlow applies element-wise operations. This is the **Hadamard product** (denoted by the $\odot$ operator, e.g., $A \odot B$) *not* **matrix multiplication**: 

In [21]:
A = np.array([[3, 4], [5, 6], [7, 8]])
A

array([[3, 4],
       [5, 6],
       [7, 8]])

In [22]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [23]:
X * A

array([[ 75,   8],
       [ 25, 156],
       [ 21,  56]])

Matrix multiplication with a vector: 

In [24]:
b = np.array([1, 2])
b

array([1, 2])

In [25]:
np.dot(A, b)

array([11, 17, 23])

Matrix multiplication with two matrices:

In [27]:
B = np.array([[1, 9], [2, 0]])
B

array([[1, 9],
       [2, 0]])

In [28]:
np.dot(A, B)

array([[11, 27],
       [17, 45],
       [23, 63]])

### Matrix Inversion

In [29]:
X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [31]:
Xinv = np.linalg.inv(X)
Xinv

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [33]:
y= np.array([4, -7])
y

array([ 4, -7])

In [35]:
w = np.dot(Xinv, y)
w

array([-1.,  4.])

Show that $y = Xw$: 

In [36]:
np.dot(X, w)

array([ 4., -7.])

## Segment 2: Eigendecomposition